### ISSUE TITLE
Mobile view improvement

### ISSUE THREAD

**Issue by Bawanthathilan** [Bawanthathilan/COVID-19-SriLanka-Tracker#1]

**Comment by copyNinja1219** [comment]
please describe the type of improvement required ?

**Comment by Bawanthathilan** [comment]
> please describe the type of improvement required ?

Mobile navbar
![image](https://user-images.githubusercontent.com/38850236/135696888-c9a6ef80-f31e-4355-afec-b53aa947cc31.png)

**Comment by OmGole** [comment]
Hi, I can fix this issue. Can you assign it to me?

**Comment by Bawanthathilan** [comment]
> Hi, I can fix this issue. Can you assign it to me?

okay

**Comment by copyNinja1219** [comment]
Hey @Bawanthathilan I just made the logo responsive & created a pr . Please check. #33
